spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**

        - id: main-service-private
          uri: lb://main-service
          predicates:
            - Path=/users/**

        - id: main-service-public
          uri: lb://main-service
          predicates:
            - Path=/events/**, /categories/**, /compilations/**, /comments/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
