server:
  port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/ewm_main_db}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  client:
    collector:
      address: ${GRPC_CLIENT_COLLECTOR_ADDRESS:static://localhost:7071}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: ${GRPC_CLIENT_ANALYZER_ADDRESS:static://localhost:7072}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

app:
  default-page-size: 10
  event:
    publication-min-hours: 1
  request:
    moderation-default: true

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
